name: Push to Main

on:
  push:
    branches: [main]

jobs:
  master-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Get NPM Version
        id: npm-version
        uses: martinbeentjes/npm-get-version-action@v1.1.0
      - run: "echo NPM Version: ${{ steps.npm-version.outputs.current-version }}"

      - name: Tag commit with updated version
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: "v${{ steps.npm-version.outputs.current-version }}"
      - name: Update release tags for latest major and minor releases
        uses: haya14busa/action-update-semver@v1
        with:
          tag: "v${{ steps.npm-version.outputs.current-version }}"
